name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.1]

    env:
      DO_COVERALLS: 18.17.1

    steps:
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ESLint
      run: npm install -g eslint

    - name: Run ESLint
      run: eslint .

    - name: Run npm install
      run: npm install

    - name: Run tests and coverage
      run: |-
        if [ "${{ matrix.node-version }}"x == "${DO_COVERALLS}"x ]
        then
          npm run coveralls
        else
          true
        fi

    - name: Run tests
      run: |-
        if [ ! "${{ matrix.node-version }}"x == "${DO_COVERALLS}"x ]
        then
          npm test
        else
          true
        fi

  notify_slack:
    if: always()
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Notify Slack
      uses: homoluctus/slatify@master
      with:
        type: ${{ needs.test.result }}
        job_name: '${{ github.repository }} - Tests '
        channel: '#whosit'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
        icon_emoji: ':mediocrebot:'
        username: 'mediocrebot'