name: Publish

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    - name: Verify tests passed
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh run list --repo ${{ github.repository }} --workflow=test.yml --branch=main --limit=1 --json conclusion --jq '.[0].conclusion' | grep -q success

    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup Node
      uses: actions/setup-node@v7
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org/

    - name: Publish
      run: npm publish --provenance

    - name: Create GitHub Release
      run: gh release create "v$(node -p "require('./package.json').version")" --generate-notes
      env:
        GH_TOKEN: ${{ github.token }}
